/**
 * object ngắn để test
 */

export default {
  CompareSAInvoiceAndPayment_sarefdate: "Receivable voucher",
  CompareSAInvoiceAndPayment_saposted_date: "Receivable voucher",
  CompareSAInvoiceAndPayment_sarefno: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainv_date: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainv_no: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainvoice_amount: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainvoice_amount_oc: "Receivable voucher",
  CompareSAInvoiceAndPayment_pay_refdate: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_posted_date: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_refno: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_amount: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_amount_oc: "Payment voucher",
  ComparePUInvoiceAndPayment_purefdate: "Receivable voucher",
  ComparePUInvoiceAndPayment_puposted_date: "Receivable voucher",
  ComparePUInvoiceAndPayment_purefno: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinv_date: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinv_no: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinvoice_amount: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinvoice_amount_oc: "Receivable voucher",
  ComparePUInvoiceAndPayment_pay_refdate: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_posted_date: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_refno: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_amount: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_amount_oc: "Payment voucher",
  TASummaryFollowTax_decription: "Tax period",
  TASummaryFollowTax_deduction_prior_period:
    "Deduction carried forward from prior period",
  TASummaryFollowTax_vat_output_amount: "Output VAT",
  TASummaryFollowTax_vat_input_amount: "Input VAT",
  TASummaryFollowTax_vat_deduction_amount: "Deduction during the period",
  TASummaryFollowTax_vat_payable_amount: "VAT payable",
  TASummaryFollowTax_vat_refund_amount: "VAT refund",
  TASummaryFollowTax_vat_input_not_refund_amount:
    "Input VAT that has not been refunded transferred during the period",
  TASummaryFollowTax_deduction_next_period:
    "Deduction carried forward to the next period",
  SalesSummaryByEmployeeAndCustomer_employee_code: "Employee ID",
  SalesSummaryByEmployeeAndCustomer_employee_name: "Employee's name",
  SalesSummaryByEmployeeAndCustomer_account_object_taxcode: "Tax code",
  SalesSummaryByEmployeeAndCustomer_account_object_mobile: "Phone number",
  SalesSummaryByEmployeeAndCustomer_contact_title: "Position",
  SalesSummaryByEmployeeAndCustomer_reduce_amount: "Allowance value",
  SalesSummaryByEmployeeAndCustomer_cost_amount: "COS",
  SalesSummaryByEmployeeAndCustomer_gross_profit_rate: "ROS (%)",
  SalesSummaryByEmployeeAndCustomer_account_object_group_code:
    "Group of customer ID",
  SalesSummaryByEmployeeAndCustomer_account_object_group_name:
    "Group of customer's name",
  GLSummaryCostByOUAndExpenseItem_accum_amount: "Accumulation",
  sa_order_voucher_no: "Order no.",
  budgeted_value: "Budgeted value",
  INSummaryOutwardByProductionOrder_inventory_out_value_in_period:
    "Material movement during period",
  INSummaryOutwardByProductionOrder_inventory_out_value_in_year:
    "Accumulated Material during period",
  difference_in_material_value: "Difference in material value",
  total_sale_amount: "Total sale amount converted",
  total_sale_amount_oc: "Total sale amount",
  total_discount_amount_oc: "Total discount amount",
  is_created_invoice: "Invoiced status",
  paid_type: "Payment status",
  outward_exported_status: "Inventory-out status",
  to_date: "To",
  invoice_type: "Type",
  send_publish_tax_status: "Status",
  invoice_status: "Invoice status",
  is_created_inward: "Inventory-in status",
  is_change_invoice: "Paper invoice transferred",
  receiver_name: "Invoice Recipient's Name",
  receiver_email: "Invoice Recipient's Email",
  payment_date: "Due date",
  close_amount: "Finalisation amount",
  receiver: "Recipient/ payer",
  open_uncompleted_amount: "Opening work in progess",
  effective_date: "Effect on",
  ref_time: "Time",
  audit_date: "Reconciliation to date",
  reason: "Purpose",
  conclusion: "Conclusion",
  note: "Note",
  invoiced_amount: "Invoiced value",
  dav_inventory_in_code: "Inventory-in voucher number in DAV database",
  voucher_national_code: "Inventory-out voucher number in DAV database",
  status_sync_medicine_national: "Synchronize with DAV database",
  SearchVoucher_total_amount_oc: "Amount",
  SearchVoucher_in_stock_code: "Receiving warehouse",
  SearchVoucher_in_stock_name: "Receiving warehouse's name",
  SearchVoucher_fixed_asset_code: "Fixed asset ID",
  SearchVoucher_fixed_asset_name: "Fixed asset's name",
  SearchVoucher_pu_order_code: "Purchase order",
  SearchVoucher_sa_order_code: "Sales order",
  SearchVoucher_refno_payment: "Payment voucher's name",
  SearchVoucher_import_export_tax_rate: "% Import/Export tax",
  SearchVoucher_import_export_tax_amount: "Import/Export tax amount",
  SearchVoucher_import_export_tax_account: "Import/Export tax account",
};
