/**
 * object mong muốn localize
 */
export default {
  CompareSAInvoiceAndPayment_sarefdate: "Receivable voucher",
  CompareSAInvoiceAndPayment_saposted_date: "Receivable voucher",
  CompareSAInvoiceAndPayment_sarefno: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainv_date: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainv_no: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainvoice_amount: "Receivable voucher",
  CompareSAInvoiceAndPayment_sainvoice_amount_oc: "Receivable voucher",
  CompareSAInvoiceAndPayment_pay_refdate: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_posted_date: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_refno: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_amount: "Payment voucher",
  CompareSAInvoiceAndPayment_pay_amount_oc: "Payment voucher",
  ComparePUInvoiceAndPayment_purefdate: "Receivable voucher",
  ComparePUInvoiceAndPayment_puposted_date: "Receivable voucher",
  ComparePUInvoiceAndPayment_purefno: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinv_date: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinv_no: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinvoice_amount: "Receivable voucher",
  ComparePUInvoiceAndPayment_puinvoice_amount_oc: "Receivable voucher",
  ComparePUInvoiceAndPayment_pay_refdate: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_posted_date: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_refno: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_amount: "Payment voucher",
  ComparePUInvoiceAndPayment_pay_amount_oc: "Payment voucher",
  TASummaryFollowTax_decription: "Tax period",
  TASummaryFollowTax_deduction_prior_period:
    "Deduction carried forward from prior period",
  TASummaryFollowTax_vat_output_amount: "Output VAT",
  TASummaryFollowTax_vat_input_amount: "Input VAT",
  TASummaryFollowTax_vat_deduction_amount: "Deduction during the period",
  TASummaryFollowTax_vat_payable_amount: "VAT payable",
  TASummaryFollowTax_vat_refund_amount: "VAT refund",
  TASummaryFollowTax_vat_input_not_refund_amount:
    "Input VAT that has not been refunded transferred during the period",
  TASummaryFollowTax_deduction_next_period:
    "Deduction carried forward to the next period",
  SalesSummaryByEmployeeAndCustomer_employee_code: "Employee ID",
  SalesSummaryByEmployeeAndCustomer_employee_name: "Employee's name",
  SalesSummaryByEmployeeAndCustomer_account_object_taxcode: "Tax code",
  SalesSummaryByEmployeeAndCustomer_account_object_mobile: "Phone number",
  SalesSummaryByEmployeeAndCustomer_contact_title: "Position",
  SalesSummaryByEmployeeAndCustomer_reduce_amount: "Allowance value",
  SalesSummaryByEmployeeAndCustomer_cost_amount: "COS",
  SalesSummaryByEmployeeAndCustomer_gross_profit_rate: "ROS (%)",
  SalesSummaryByEmployeeAndCustomer_account_object_group_code:
    "Group of customer ID",
  SalesSummaryByEmployeeAndCustomer_account_object_group_name:
    "Group of customer's name",
  GLSummaryCostByOUAndExpenseItem_accum_amount: "Accumulation",
  sa_order_voucher_no: "Order no.",
  budgeted_value: "Budgeted value",
  INSummaryOutwardByProductionOrder_inventory_out_value_in_period:
    "Material movement during period",
  INSummaryOutwardByProductionOrder_inventory_out_value_in_year:
    "Accumulated Material during period",
  difference_in_material_value: "Difference in material value",
  total_sale_amount: "Total sale amount converted",
  total_sale_amount_oc: "Total sale amount",
  total_discount_amount_oc: "Total discount amount",
  is_created_invoice: "Invoiced status",
  paid_type: "Payment status",
  outward_exported_status: "Inventory-out status",
  to_date: "To",
  invoice_type: "Type",
  send_publish_tax_status: "Status",
  invoice_status: "Invoice status",
  is_created_inward: "Inventory-in status",
  is_change_invoice: "Paper invoice transferred",
  receiver_name: "Invoice Recipient's Name",
  receiver_email: "Invoice Recipient's Email",
  payment_date: "Due date",
  close_amount: "Finalisation amount",
  receiver: "Recipient/ payer",
  open_uncompleted_amount: "Opening work in progess",
  effective_date: "Effect on",
  ref_time: "Time",
  audit_date: "Reconciliation to date",
  reason: "Purpose",
  conclusion: "Conclusion",
  note: "Note",
  invoiced_amount: "Invoiced value",
  dav_inventory_in_code: "Inventory-in voucher number in DAV database",
  voucher_national_code: "Inventory-out voucher number in DAV database",
  status_sync_medicine_national: "Synchronize with DAV database",
  SearchVoucher_total_amount_oc: "Amount",
  SearchVoucher_in_stock_code: "Receiving warehouse",
  SearchVoucher_in_stock_name: "Receiving warehouse's name",
  SearchVoucher_fixed_asset_code: "Fixed asset ID",
  SearchVoucher_fixed_asset_name: "Fixed asset's name",
  SearchVoucher_pu_order_code: "Purchase order",
  SearchVoucher_sa_order_code: "Sales order",
  SearchVoucher_refno_payment: "Payment voucher's name",
  SearchVoucher_import_export_tax_rate: "% Import/Export tax",
  SearchVoucher_import_export_tax_amount: "Import/Export tax amount",
  SearchVoucher_import_export_tax_account: "Import/Export tax account",
  SearchVoucher_special_consume_tax_rate: "% Special Consumption tax",
  SearchVoucher_special_consume_tax_amount: "Special Consumption Tax amount",
  SearchVoucher_special_consume_tax_account: "Special Consumption Tax account",
  SearchVoucher_environmental_tax_amount: "Environment Protection Tax amount",
  SearchVoucher_environmental_tax_account: "Environment Protection Tax account",
  SearchVoucher_vat_rate: "%VAT",
  SearchVoucher_tax_account_object_code: "Tax subject",
  SearchVoucher_tax_account_object_name: "Tax subject's name",
  DICustomer_closing_amount: "Liabilities",
  DICustomer_company_tax_code: "Tax code",
  DICustomer_issue_date: "Issued date",
  DICustomer_issue_by: "Issued by",
  DICustomer_due_time: "Pay within days",
  DICustomer_receive_account: "Account Receivable",
  DICustomer_bank_branch_name: "Bank's branch",
  DICustomer_bank_province_or_city: "Bank's location",
  DICustomer_country: "Nation",
  DICustomer_prefix: "Title",
  DICustomer_contact_address: "Contact address",
  DICustomer_legal_representative: "Legal representative",
  DICustomer_einvoice_contact_name: "Invoice recipient",
  DICustomer_einvoice_contact_mobile: "Phone number",
  DICustomer_einvoice_contact_email: "Email",
  DICustomer_account_object_type: "Organisation/Individual",
  DICustomer_is_vendor: "Is a supplier",
  AccountObject_issue_date: "Issued date",
  AccountObject_issue_by: "Issued by",
  AccountObject_bank_branch_name: "Bank's branch",
  AccountObject_legal_representative: "Legal representative",
  AccountObject_account_object_type: "Organisation/Individual",
  DIVendor_issue_date: "Issued date",
  DIVendor_issue_by: "Issued by",
  DIVendor_receive_account: "Account Receivable",
  DIVendor_bank_branch_name: "Bank's branch",
  DIVendor_contact_address: "Contact address",
  DIVendor_legal_representative: "Legal representative",
  DIVendor_einvoice_contact_name: "Invoice recipient",
  DIVendor_einvoice_contact_mobile: "Phone number",
  DIVendor_einvoice_contact_email: "Email",
  DIVendor_account_object_type: "Organisation/Individual",
  DIVendor_is_vendor: "Is a supplier",
  DIVendor_website: "Website",
  DIVendor_is_customer: "Is a customer",
  DIEmployee_gender: "Gender",
  DIEmployee_company_tax_code: "Tax code",
  DIEmployee_issue_date: "Issue date",
  DIEmployee_issue_by: "Issue by",
  DIEmployee_agreement_salary: "Agreement salary",
  DIEmployee_salary_coefficient: "Salary Coefficient",
  DIEmployee_insurance_salary: "Insurance salary",
  DIEmployee_number_of_dependent: "Number of dependent",
  DIEmployee_employee_tax_code: "Tax code",
  DIEmployee_employee_contract_type: "Contract type",
  DIEmployee_bank_branch_name: "Bank branch name",
  DIEmployee_is_customer: "Is a customer",
  DIInventoryItem_image: "Image",
  DIInventoryItem_inventory_item_type: "Characteristics ",
  DIInventoryItem_inventory_item_category_code_list: "Group of items",
  DIInventoryItem_sale_description: "Description on Sales voucher",
  DIInventoryItem_inventory_account: "Inventory Account",
  DIInventoryItem_sale_account: "Sales Account",
  DIInventoryItem_sale_off_account: "Sales allowance Account",
  DIInventoryItem_return_account: "Returned Account",
  DIInventoryItem_tax_rate: "VAT tax rate",
  DIInventoryItem_import_tax_rate: "Import tax",
  DIInventoryItem_inventory_category_special_tax_name:
    "Group of items subjected to Special Consumption Tax",
  DIInventoryItem_status_sync_medicine_national:
    "Synchronize with DAV database",
  DIInventoryItem_is_drug: "Drug items",
  DIInventoryItem_drug_national_code: "DAV's code",
  DIInventoryItem_other_vat_rate: "Other tax rate",
  AccumGLF01_DN_10_account_number: "Account number",
  PULiabilitiesSummaryByEmployee_01_account_number: "Liability Account",
  PULiabilitiesSummaryByEmployee_10_account_number: "Liability Account",
  ReceivableDeptSummary_account_object_category_name:
    "Group of customers' name",
  PUDetailPurchaseByInventoryItemDynamic_10_account_object_category_name:
    "Group of suppliers' name",
  CACashDetailBook_account_object_code: "Subject ID",
  CACashDetailBook_account_object_name: "Subject's name",
  GLAccountLedger_account_object_code: "Subject ID",
  GLAccountLedgerDetail_account_object_code: "Subject ID",
  INInventoryBookDetail_account_object_code: "Subject ID",
  INInventoryBookDetailByLotNo_10_account_object_code: "Subject ID",
  INInventoryBookDetailBySerialNumber_10_account_object_code: "Subject ID",
  CTIncomeDetailByContract_10_account_object_code: "Customer ID",
  CTIncomeSummaryByContract_00_account_object_code: "Customer ID",
  IncomeDetailBySAOrder_10_account_object_code: "Customer ID",
  SAInvoiceDiaryBook_10_account_object_code: "Customer ID",
  SalesBookDetailByEmployee_10_account_object_code: "Customer ID",
  SalesBookDetailBySerial_00_account_object_code: "Customer ID",
  SalesBookDetailBySerial_00_description: "Item's name in voucher",
  SalesBookDetailDefault_10_account_object_code: "Customer ID",
  SalesSummaryByCustomer_10_account_object_code: "Customer ID",
  PUDetailPurchaseByInventoryItemDynamic_10_account_object_code: "Supplier ID",
  PUDiary_10_account_object_code: "Supplier ID",
  PULiabilitiesSummaryByEmployee_01_account_object_code: "Supplier ID",
  PULiabilitiesSummaryByEmployee_10_account_object_code: "Supplier ID",
  ReceivableDetailBySAOrder_account_object_group_code_list:
    "Group of customers's ID",
};
